#Análisis de Datos con NumPy (Core)

## Instrucciones

Descripción del Problema: Imagina que estás trabajando como analista de datos para una empresa que recopila información sobre las ventas diarias de diferentes productos en varias tiendas. Necesitas analizar estos datos para extraer información útil y presentar un resumen de las ventas.
## Requisitos del Sistema:
El programa debe generar datos de ventas de manera aleatoria para 10 productos diferentes en 5 tiendas distintas durante 7 días (una semana).

Los datos deben estar almacenados en un array de NumPy de 3 dimensiones (productos, tiendas, días).

Debes calcular y mostrar la siguiente información:

Total de ventas por producto a lo largo de la semana.

Total de ventas por tienda a lo largo de la semana.

Promedio de ventas por producto por día.

Promedio de ventas por tienda por día.

Producto con mayor y menor ventas totales en la semana.

Tienda con mayor y menor ventas totales en la semana.

## Detalles Específicos:
Genera los datos de ventas aleatorias usando np.random.randint, con valores entre 0 y 100.

Usa funciones de NumPy para calcular las sumas y promedios.

Maneja posibles errores o valores inesperados.

Presenta los resultados de manera clara y estructurada.
## Consideraciones Adicionales:
Organiza tu código utilizando funciones para cada una de las tareas principales.

Usa comentarios para explicar cada sección de tu código.

Asegúrate de que el código sea robusto y maneje casos en los que los datos generados puedan estar fuera de los rangos esperados.

In [4]:
import numpy as np

In [31]:
def generar_datos_ventas(productos, tiendas, dias):
  """
    Genera datos de ventas aleatorias para el número de productos, tiendas y días especificados
  """

  return np.random.randint(0, 101, (productos, tiendas, dias))

In [38]:
datos = generar_datos_ventas(3,2,2)
print(datos)

[[[ 9 73]
  [55 99]]

 [[29 67]
  [15 16]]

 [[25 90]
  [52  8]]]


In [37]:
def calcular_totales_ventas_por_producto(datos):
    # Calcula el total de ventas por producto a lo largo de la semana
    return np.sum(datos, axis=(1, 2))

In [20]:
print(calcular_totales_ventas_por_producto(datos))

[454 232]


In [22]:
def calcular_totales_ventas_por_tienda(datos):
    # Calcula el total de ventas por tienda a lo largo de la semana
    return np.sum(datos, axis=(0, 2))

In [23]:
print(calcular_totales_ventas_por_tienda(datos))

[232 197 257]


In [24]:
def calcular_promedio_ventas_por_producto(datos):
    # Calcula el promedio de ventas por producto por día
    return np.mean(datos, axis=(1, 2))

In [34]:
totales_por_producto = calcular_promedio_ventas_por_producto(datos)
print(totales_por_producto)

[66.25 69.75 52.  ]


In [26]:
def calcular_promedio_ventas_por_tienda(datos):
    # Calcula el promedio de ventas por tienda por día
    return np.mean(datos, axis=(0, 2))



In [27]:
print(calcular_promedio_ventas_por_tienda(datos))

[58.   49.25 64.25]


In [43]:
def encontrar_producto_mayor_menor_ventas(totales_por_producto):
    # Encuentra el producto con mayor y menor ventas totales en la semana
    producto_mayor_ventas = np.argmax(totales_por_producto)
    producto_menor_ventas = np.argmin(totales_por_producto)
    return producto_mayor_ventas, producto_menor_ventas

In [44]:
print(encontrar_producto_mayor_menor_ventas(totales_por_producto))

(np.int64(3), np.int64(9))


In [45]:
def encontrar_tienda_mayor_menor_ventas(totales_por_tienda):
    # Encuentra la tienda con mayor y menor ventas totales en la semana
    tienda_mayor_ventas = np.argmax(totales_por_tienda)
    tienda_menor_ventas = np.argmin(totales_por_tienda)
    return tienda_mayor_ventas, tienda_menor_ventas

In [39]:
productos = 10
tiendas = 5
dias = 7

In [40]:
# Genera los datos de ventas
datos = generar_datos_ventas(productos, tiendas, dias)


In [41]:
# Calcula los totales y promedios
totales_por_producto = calcular_totales_ventas_por_producto(datos)
totales_por_tienda = calcular_totales_ventas_por_tienda(datos)
promedio_por_producto = calcular_promedio_ventas_por_producto(datos)
promedio_por_tienda = calcular_promedio_ventas_por_tienda(datos)

In [46]:
# Encuentra el producto y la tienda con mayor y menor ventas
producto_mayor_ventas, producto_menor_ventas = encontrar_producto_mayor_menor_ventas(totales_por_producto)
tienda_mayor_ventas, tienda_menor_ventas = encontrar_tienda_mayor_menor_ventas(totales_por_tienda)

In [47]:
# Imprime los resultados
print("Total de ventas por producto a lo largo de la semana:", totales_por_producto)
print("Total de ventas por tienda a lo largo de la semana:", totales_por_tienda)
print("Promedio de ventas por producto por día:", promedio_por_producto)
print("Promedio de ventas por tienda por día:", promedio_por_tienda)
print(f"Producto con mayor ventas: Producto {producto_mayor_ventas}")
print(f"Producto con menor ventas: Producto {producto_menor_ventas}")
print(f"Tienda con mayor ventas: Tienda {tienda_mayor_ventas}")
print(f"Tienda con menor ventas: Tienda {tienda_menor_ventas}")

Total de ventas por producto a lo largo de la semana: [1772 1743 1943 2042 1922 1843 1810 1725 1763 1656]
Total de ventas por tienda a lo largo de la semana: [3344 3423 3891 3617 3944]
Promedio de ventas por producto por día: [50.62857143 49.8        55.51428571 58.34285714 54.91428571 52.65714286
 51.71428571 49.28571429 50.37142857 47.31428571]
Promedio de ventas por tienda por día: [47.77142857 48.9        55.58571429 51.67142857 56.34285714]
Producto con mayor ventas: Producto 3
Producto con menor ventas: Producto 9
Tienda con mayor ventas: Tienda 4
Tienda con menor ventas: Tienda 0
